### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by JagaRamesh** [toolatetofail/intro-data-capstone-biodiversity#1]
Overall, Excellent job explaining the analysis and the outcome in the document.

The Summaries highlighted for “Endangerment of Species” and “Foot & Mouth disease for Sheep  in Parks“ are accurate. It’s good  to see the code being shared through GITHUB link, as the project is completed in “codecademy” site. The Matplotlib graphs are neat with proper title and xlabel and ylabel defined.

One small bit of information I noticed was missing in the final summary of “Foot & Mouth disease in sheep”. The number of weeks was mentioned for “Yellowstone national park” but not for “Bryce National Park”. 

Great work! KEEP IT UP!

**Comment by toolatetofail** [comment]
Hi JagaRamesh! Thanks for the highlight! I have uploaded a revised version (version 2) with an update on Bryce National Park. Thanks!

**Comment by toolatetofail** [comment]
Hi Jaga, is my revised version okay?
